version: '3.8'

# Docker Compose override for GitHub Actions / CI environments
# This configuration excludes iOS/macOS builds which are not supported on Linux runners

services:
  # Password Manager API for CI
  password-manager-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-api
      args:
        BUILD_CONFIGURATION: Release
    container_name: password-manager-api-ci
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - password-manager-network
    depends_on:
      - database

  # Password Manager Web for CI
  password-manager-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-web
      args:
        BUILD_CONFIGURATION: Release
    container_name: password-manager-web-ci
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - password-manager-network
    depends_on:
      - database
      - password-manager-api

  # MAUI Android build for CI (build only, no runtime)
  password-manager-maui-android:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-maui-android
      args:
        BUILD_CONFIGURATION: Release
        MAUI_TARGET_FRAMEWORK: net9.0-android
    container_name: password-manager-maui-android-ci
    volumes:
      - ./artifacts:/app/publish/maui-android
    networks:
      - password-manager-network
    command: echo "MAUI Android build completed"

  # Database for CI
  database:
    image: postgres:16
    container_name: password-manager-db-ci
    environment:
      - POSTGRES_DB=passwordmanager
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - password-manager-network

volumes:
  artifacts:

networks:
  password-manager-network:
    driver: bridge
