version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - dotnet-nuget:/home/vscode/.nuget
      - dotnet-workloads:/usr/share/dotnet/sdk-manifests
    command: sleep infinity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    networks:
      - dev-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - dev-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: PasswordManagerDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
  dotnet-nuget:
  dotnet-workloads:
  sqlserver-data:
  postgres-data:

networks:
  dev-network:
    driver: bridge
